import {extraQuestions,extraMatches} from './extra-questions';
export const base='https://learn.microsoft.com/en-us/training/modules/';
export const topics=[
{title:'Cloud computing',short:'Cloud concepts',source:'describe-cloud-compute/',lead:'Rent computing resources over the internet and adjust capacity as demand changes.',rows:[['Public cloud','A third-party provider offers services to many customers. Public does not mean your data is publicly accessible.'],['Private cloud','Resources dedicated to one organization, hosted on-site or elsewhere. More control also brings more management responsibility.'],['Hybrid cloud','Connected public and private environments; useful when some workloads stay private while others use public capacity.'],['Multicloud','Using more than one public cloud provider. Azure Arc helps manage resources across Azure, on-premises, and other clouds.'],['Consumption & costs','Pay for consumed resources. CapEx buys assets upfront; OpEx pays ongoing operating costs. Release unused resources to reduce spend.']],tip:'Deployment model = where it runs. Service model = what you manage.'},
{title:'Benefits of cloud services',short:'Cloud benefits',source:'describe-benefits-use-cloud-services/',lead:'Know what each benefit means, and what a scenario is really asking for.',rows:[['Availability & reliability','High availability minimizes downtime. Reliability means recovering from failures and continuing to function. SLA commitments depend on the service and configuration.'],['Scale up / down','Vertical scaling changes the power of an instance, such as CPU or RAM.'],['Scale out / in','Horizontal scaling adds or removes instances. Elasticity matches capacity to changing demand, often through autoscaling.'],['Predictability','Estimate performance needs and costs using monitoring, usage trends, autoscaling, load balancing, and pricing tools.'],['Security & governance','Security protects systems and data. Governance applies standards, policies, and compliance controls consistently.'],['Sustainability','Right-size resources, scale down when demand drops, and shut down unused environments. Monitor usage to reduce wasted energy and cost.'],['Manageability','Manage resources with templates, monitoring, and automation. Access management tools through the portal, CLI, APIs, or PowerShell.']],tip:'More powerful machine = vertical. More machines = horizontal.'},
{title:'Shared responsibility',short:'Responsibility',source:'describe-cloud-compute/4-describe-shared-responsibility-model',lead:'Moving to the cloud changes your responsibilities; it does not eliminate them.',rows:[['Always the customer','Protect your data, accounts and identities, and the devices connecting to your environment. Decide who should have access.'],['Always the provider','Secure and operate physical datacenters, physical networking, and physical hosts.'],['IaaS','You manage the guest operating system, patches, installed applications, and workload configuration.'],['PaaS','The provider manages the platform and operating system. You manage your application code, data, and access configuration.'],['SaaS','The provider operates the application and underlying stack. You still manage your data, users, and appropriate access.']],tip:'Identity and access can be shared: you configure users and roles while the provider operates the identity platform.'},
{title:'IaaS, PaaS, and SaaS',short:'Service types',source:'describe-cloud-service-types/',lead:'Choose the level of control and operational work your application needs.',rows:[['IaaS → rent infrastructure','Example: Azure Virtual Machines. Best when you need OS control, custom software, or a lift-and-shift migration. Most customer management of the three models.'],['PaaS → build applications','Example: Azure App Service or a managed database. Focus on code and data while Microsoft maintains the underlying platform.'],['SaaS → use an application','Example: Microsoft 365. A finished application operated by the provider; least infrastructure management for the customer.']],tip:'Rent → build → use. More provider management generally means less control over the underlying stack.'},
{title:'Azure architecture',short:'Architecture',source:'describe-core-architectural-components-of-azure/',lead:'Separate physical placement from the hierarchy used to organize and govern resources.',rows:[['Region','A geographic area containing nearby, connected datacenters. Region choice affects latency, service availability, and data location.'],['Availability zone','One or more physically separate datacenters within a region, with independent power, cooling, and networking. Zone support varies by region and service.'],['Region pairs & sovereign regions','Region pairs support geographic resilience, but pairing does not automatically replicate every workload. Sovereign regions are isolated environments for specific requirements.'],['Management hierarchy','Management groups → subscriptions → resource groups → resources. Policies and access assignments can inherit down the hierarchy.'],['Resource group','A lifecycle and management container. A grouped resource belongs to one group at a time; groups cannot nest. Deleting a group deletes its contained resources.'],['Subscription & management group','A subscription provides a billing and access boundary. A management group applies governance across multiple subscriptions.']],tip:'Zones are within a region. Management groups are above subscriptions.'},
{title:'Compute: choose the right service',short:'Compute',source:'describe-azure-compute-networking-services/',lead:'Look for the workload requirement before selecting the product.',rows:[['Virtual Machines','OS control and custom software. Plan CPU/RAM, disks, and networking. You patch the guest OS.'],['Scale sets vs. availability sets','Scale sets manage groups of VMs and support scaling. Availability sets spread VMs across fault domains (hardware risks) and update domains (maintenance).'],['Containers','Package an application and dependencies in lightweight isolated environments. ACI runs containers simply; Container Apps adds managed scaling; AKS orchestrates container fleets.'],['Azure Functions','Event-driven serverless code, such as processing a file upload. You focus on code; the platform operates the compute infrastructure.'],['App Service','Managed hosting for web apps and APIs, without managing the underlying OS.'],['Azure Virtual Desktop','Deliver centrally managed Windows desktops and applications to users on different devices.']],tip:'Full OS control → VM. Managed web hosting → App Service. Event-triggered code → Functions.'},
{title:'Storage, resilience, and migration',short:'Storage',source:'describe-azure-storage-services/',lead:'Match the data format, access frequency, and failure protection to the requirement.',rows:[['Storage services','Blob: objects such as images and backups. Files: managed SMB/NFS file shares. Queue: messages between components. Table: structured NoSQL entities. Managed disks: VM block storage.'],['Blob access tiers','Hot: frequent access. Cool: infrequent access, 30-day minimum retention for early-deletion charges. Cold: rarer access, 90 days. Archive: offline, 180 days; rehydrate before reading.'],['LRS & ZRS','LRS keeps three copies in one datacenter. ZRS synchronously spreads copies across three zones in the primary region.'],['GRS & GZRS','GRS adds asynchronous replication to another region to LRS. GZRS combines primary-region zone redundancy with secondary-region replication. Async replication can lose recent writes after failure.'],['Read-access variants','RA-GRS and RA-GZRS enable reads from the secondary region without waiting for failover. Durability of stored data is different from service uptime.'],['Move files','AzCopy: command-line transfers. Storage Explorer: graphical management. Azure File Sync: synchronize/cache Azure file shares on Windows servers.'],['Migrate workloads','Azure Migrate helps discover, assess, and migrate workloads. Azure Data Box moves large datasets using physical devices when network transfer is impractical.']],tip:'L = local. Z = zones. G = geographic. RA = read access to the secondary.'},
{title:'Azure Cosmos DB',short:'Cosmos DB',source:'explore-non-relational-data-stores-azure/2-describe-azure-cosmos-db',lead:'A fully managed NoSQL database for flexible data, global distribution, and low-latency applications.',rows:[['Flexible schema','Items in a container can have different properties. Useful for changing product catalogs, user profiles, gaming, and telemetry.'],['Data hierarchy','Account → database → container → item. A partition key distributes data; a well-chosen key spreads workload evenly.'],['Global distribution','Replicate data to selected regions near users. Multi-region configurations improve reach and resilience.'],['Consistency','Strong prioritizes fresh reads; eventual allows replicas to converge over time. Session guarantees apply within a client session. Bounded staleness and consistent prefix offer other trade-offs.'],['Throughput','Operations consume Request Units (RUs); provisioned throughput is measured in RU/s. Autoscale adjusts capacity within a configured range. Serverless bills for consumed requests and has different capabilities.'],['Choose carefully','Good for scalable operational NoSQL workloads. Complex relational joins often suit Azure SQL better; large historical analytics call for analytical services.']],tip:'Cosmos DB is a database, not a file share or a replacement for every relational workload.'},
{title:'The commercial marketplace',short:'Marketplace',source:'intro-commercial-marketplace/',lead:'Use the storefront distinctions taught in your assigned module to understand discovery and purchasing.',rows:[['Azure Marketplace','Azure-focused IT solutions: infrastructure, applications, and partner services. Accessible on the web and through the Azure portal.'],['Microsoft AppSource','Business applications and services, including integrations with Dynamics 365, Microsoft 365, and Power Platform. Also discovered within products.'],['Listing choices','Contact me generates a sales contact. Free trial lets customers evaluate. BYOL uses an existing license. Transact enables purchase through Microsoft commerce.'],['Private offers','Customer-specific commercial offers can include negotiated pricing and terms. They are different from private-cloud deployment.'],['Partner Center & Rewards','Partner Center helps publishers manage offers and leads. Marketplace Rewards provides eligible marketing and sales benefits to help publishers go to market.']],tip:'Marketplace listing ≠ automatically free. “Get it now” can involve different licensing and payment arrangements.'}
];
export type Question={id:number;topic:number;q:string;options:string[];answer:number;why:string};
const raw:[number,string,string[],number,string][]=[
[0,'A company connects its private cloud to Azure to handle seasonal demand. Which model is this?',['Public only','Hybrid','SaaS','Multicloud'],1,'Hybrid connects public and private cloud environments.'],
[0,'Which expense is the clearest example of CapEx?',['Monthly cloud usage','Per-request billing','Buying physical servers upfront','A monthly software subscription'],2,'CapEx buys long-lived assets upfront; ongoing service consumption is OpEx.'],
[0,'What does a consumption-based model charge for?',['Resources consumed','A guaranteed flat bill for all workloads','Only physical hardware purchases','Only resources outside business hours'],0,'Cloud charges follow the services and resources consumed.'],
[1,'Increasing the RAM of an existing VM is which kind of scaling?',['Horizontal out','Horizontal in','Geographic','Vertical up'],3,'Vertical scaling changes an instance’s capacity; horizontal scaling changes the instance count.'],
[1,'A system recovers after a failure and continues to operate. Which benefit is highlighted?',['Governance','Reliability','CapEx','Licensing'],1,'Reliability concerns recovery and continued operation after failure.'],
[1,'A team uses templates and audits to enforce deployment standards. What is the main goal?',['Governance','Adding CPU','Buying hardware','Changing the deployment model'],0,'Governance establishes and checks consistent standards across resources.'],
[2,'Who remains responsible for deciding which employees should access cloud data?',['Only Microsoft in every model','The datacenter landlord','The customer','Nobody when using SaaS'],2,'Customers retain responsibility for their data, identities, and appropriate access.'],
[2,'Who patches the guest operating system on a customer-managed Azure VM?',['The SaaS vendor','The customer','The physical datacenter team','The internet provider'],1,'A VM is IaaS; guest OS maintenance stays with the customer.'],
[2,'Which responsibility belongs to the cloud provider across IaaS, PaaS, and SaaS?',['Choosing customer passwords','Classifying customer data','Approving customer users','Securing physical hosts'],3,'Physical infrastructure is operated and secured by the provider.'],
[3,'You want to deploy a web application without maintaining its OS. Which model fits?',['PaaS','Private cloud only','On-premises only','IaaS'],0,'PaaS supplies a managed platform while you focus on your application.'],
[3,'A team uses a complete provider-operated email application. Which service model is this?',['IaaS','Hybrid','SaaS','PaaS'],2,'SaaS provides a finished application rather than an infrastructure or development platform.'],
[3,'Which model gives the customer the most guest OS control?',['SaaS','IaaS','PaaS','All give the same OS control'],1,'IaaS allows OS and software configuration, with more operational responsibility.'],
[4,'What is an Azure availability zone?',['A separate subscription','A group of paired regions','A billing scope','An isolated datacenter grouping within a region'],3,'Zones provide separate power, cooling, and networking within a region.'],
[4,'Which hierarchy is correctly ordered from broadest to narrowest?',['Management group → subscription → resource group → resource','Subscription → management group → resource → resource group','Resource group → subscription → region → resource','Region → resource group → management group → resource'],0,'Management groups govern subscriptions, which contain resource groups and resources.'],
[4,'Does choosing a paired region automatically replicate every application?',['Yes, including every VM','Only if the resource group is renamed','No; replication and recovery depend on the service and configuration','Yes, for all IaaS workloads'],2,'Region pairing does not configure cross-region replication for every service.'],
[5,'Which service is best suited to running code when a new file is uploaded?',['Azure Files','Azure Functions','Azure Virtual Desktop','Management groups'],1,'Functions runs event-triggered code without managing the underlying servers.'],
[5,'You need a managed fleet of VMs that can increase its instance count with demand. Choose:',['Availability sets','Blob Storage','AppSource','Virtual Machine Scale Sets'],3,'Scale sets manage VM groups and support scaling; availability sets focus on failure isolation.'],
[5,'Which service orchestrates a fleet of Kubernetes containers?',['AKS','Azure File Sync','Azure Data Box','Azure Virtual Desktop'],0,'Azure Kubernetes Service provides managed Kubernetes orchestration.'],
[5,'Which service delivers cloud-hosted Windows desktops to remote staff?',['Azure Functions','Azure Queue Storage','Azure Virtual Desktop','Azure Cosmos DB'],2,'Virtual Desktop centralizes Windows desktop and application delivery.'],
[6,'An application must store images and video as objects. Choose:',['Azure Files','Azure Blob Storage','Azure Queue Storage','Azure Table Storage'],1,'Blob Storage is designed for object data such as media and backups.'],
[6,'Which option replicates synchronously across three zones in one region?',['LRS','GRS','RA-GRS','ZRS'],3,'ZRS spreads primary-region copies across availability zones.'],
[6,'Which blob tier requires rehydration before normal reads?',['Archive','Hot','Cool','Cold'],0,'Archive is offline storage. Hot, cool, and cold are online tiers.'],
[6,'Which tool transfers a large dataset using a physical device?',['Azure File Sync','Azure DNS','Azure Data Box','Azure Functions'],2,'Data Box is an offline physical transfer option for large migrations.'],
[6,'What does RA add to RA-GRS?',['Synchronous cross-region writes','Read access to the secondary region','Automatic application redesign','Copies in every Azure region'],1,'RA enables reads against the secondary; replication remains asynchronous across regions.'],
[7,'Which workload is the strongest fit for Cosmos DB?',['A shared SMB drive','Complex multi-table relational joins as the main requirement','A virtual desktop pool','A globally distributed app with flexible JSON records'],3,'Cosmos DB suits flexible NoSQL data and global operational workloads.'],
[7,'What is the role of a Cosmos DB partition key?',['Distribute items across logical partitions','Encrypt a VM disk','Choose an AppSource category','Create a physical network cable'],0,'A good partition key helps distribute data and request load.'],
[7,'What does RU/s describe in Cosmos DB?',['Number of users','Region distance','Provisioned request throughput per second','Number of file shares'],2,'Request Units measure operation cost; RU/s is throughput capacity.'],
[8,'In the assigned module, which storefront emphasizes business apps for Microsoft 365 and Dynamics 365?',['Azure Files','Microsoft AppSource','Azure Resource Manager','Azure Data Box'],1,'AppSource emphasizes business applications and product integrations.'],
[8,'A customer already owns a software license and wants to apply it to an offer. Which listing fits?',['Contact me','Free trial','Transact only','BYOL'],3,'Bring your own license uses an existing license rather than purchasing that license through Microsoft commerce.'],
[8,'What is the purpose of a marketplace private offer?',['Negotiate customer-specific commercial terms','Build a private datacenter','Make every product free','Create a resource group'],0,'Private offers allow tailored pricing and terms for particular customers.']
];
export const questions:Question[]=[...raw,...extraQuestions].map(([topic,q,options,answer,why],id)=>({id,topic,q,options,answer,why}));
export const matchSets=[
{title:'Cloud vocabulary',topic:0,pairs:[['IaaS','Infrastructure with customer-managed guest OS'],['PaaS','Managed platform for your application code'],['SaaS','A complete provider-operated application'],['Hybrid cloud','Connected public and private cloud environments'],['OpEx','Ongoing operating expenditure']]},
{title:'Azure organization',topic:4,pairs:[['Management group','Governance across subscriptions'],['Subscription','Billing and access boundary'],['Resource group','Lifecycle container for related resources'],['Availability zone','Independent datacenter grouping within a region'],['Region','Geographic area containing connected datacenters']]},
{title:'Pick a storage or data service',topic:6,pairs:[['Blob Storage','Object data such as photos and videos'],['Azure Files','Managed network file shares'],['Queue Storage','Messages for asynchronous processing'],['Azure Cosmos DB','Globally distributed flexible NoSQL database'],['Azure Data Box','Physical transfer of large datasets']]},
{title:'Tools and resilience',topic:6,pairs:[['AzCopy','Command-line file transfers'],['Storage Explorer','Graphical storage management'],['Azure File Sync','Windows Server synchronization with Azure file shares'],['LRS','Three copies in one datacenter'],['GZRS','Primary-zone redundancy plus secondary-region replication']]}
,...extraMatches
];