export const deeper = [
 {sections:[
 ['How the pieces fit together','Compute runs your code, storage keeps data, and networking connects components. A cloud provider makes these capabilities available as services. Moving online does not automatically make a solution scalable or resilient: you still choose the resources and configure the application.'],
 ['Worked example: a seasonal shop','Imagine a retailer that needs six application instances during a sale and two afterward. Adding four instances handles the extra demand; removing them afterward avoids paying for unnecessary capacity. Keeping a private inventory system connected to that public-cloud shop would make the overall deployment hybrid. Using Azure plus another public provider would make it multicloud.'],
 ['Avoid these mix-ups','Private cloud describes exclusive use by one organization, not necessarily a room in its own building. Public cloud describes who can purchase services, not permission to read your data. A cloud model and a service model answer different questions: an Azure VM can be both public-cloud deployment and IaaS.']],
 recall:'A company uses two public providers and no private cloud. Is that automatically hybrid?',answer:'No. That is multicloud. Hybrid requires connected public and private environments.',links:[['Cloud models','describe-cloud-compute/5-define-cloud-models'],['Consumption and costs','describe-cloud-compute/6-describe-consumption-based-model']]},
 {sections:[
 ['Capacity, automation, and traffic','Scalability is the ability to change capacity. Elasticity is adjusting it as demand changes. Autoscaling automates that adjustment; load balancing distributes incoming requests across instances. These ideas work together, but adding a load balancer alone does not create more compute capacity.'],
 ['Worked example: a ticket launch','A ticket site expects a traffic spike at noon. It can scale out its web tier and balance requests across those instances, then scale in afterward. Monitoring tells the team whether response times improve. Recovery planning addresses what happens when an instance or location fails. Each action solves a different part of the problem.'],
 ['Operational habits matter','A cloud bill is not automatically predictable just because it is pay-as-you-go. Track consumption, compare it with estimates, and remove waste. Templates improve repeatability; alerts make problems visible. Right-sizing a development environment and deallocating unused compute can support both cost efficiency and sustainability.']],
 recall:'Does adding two VMs mean vertical or horizontal scaling?',answer:'Horizontal scale-out. Vertical scaling changes the capacity of an existing instance.',links:[['Availability and scaling','describe-benefits-use-cloud-services/2-high-availability-scalability-cloud'],['Reliability and predictability','describe-benefits-use-cloud-services/3-reliability-predictability-cloud'],['Manageability','describe-benefits-use-cloud-services/5-manageability-cloud']]},
 {sections:[
 ['Follow the layer being discussed','Start by identifying the service model, then identify the layer: physical hardware, guest OS, application, or customer data. The phrase “Microsoft manages the service” does not mean Microsoft makes your business decisions about access or data handling.'],
 ['Worked example: the same database, two ways','Suppose you install database software on a VM. Your team maintains the VM operating system and the database software. Choose a managed database platform instead, and the provider takes over platform maintenance. In both cases, your team decides what records to store and who may use them.'],
 ['Why this matters in scenarios','An employee sharing confidential records too broadly is an access and data-handling issue. A failed physical server is a provider infrastructure issue. A vulnerable guest OS on a customer-managed VM is a customer maintenance issue. Classify the layer first instead of assuming every cloud incident has the same owner.']],
 recall:'Does switching from IaaS to SaaS remove responsibility for employee access?',answer:'No. The provider manages more of the technology stack, but customers still manage appropriate access to their data.',links:[['Responsibility model','describe-cloud-compute/4-describe-shared-responsibility-model'],['IaaS responsibilities','describe-cloud-service-types/2-describe-infrastructure-service']]},
 {sections:[
 ['A decision process','Ask three questions. Do I need to control the OS? IaaS is a candidate. Do I want to write and deploy my own application without operating the platform? Consider PaaS. Do I mainly need to use a finished application? Consider SaaS. Start with the requirement, not a product name.'],
 ['Worked example: one business, three models','A design firm might use a VM for legacy software needing custom OS settings, App Service for its customer portal, and a finished cloud email product for staff. That is a reasonable mix of IaaS, PaaS, and SaaS. An organization does not have to choose one model for everything.'],
 ['The trade-off','Control and operational effort move together. Renting a VM removes physical hardware work but leaves software maintenance. A managed platform reduces that maintenance while constraining underlying configuration choices. A finished application reduces implementation effort further, but you work within the features and configuration the product offers.']],
 recall:'Is an application PaaS merely because you access it in a browser?',answer:'No. Browser access does not determine the service model. Ask whether you are using a finished application or building on a managed platform.',links:[['IaaS','describe-cloud-service-types/2-describe-infrastructure-service'],['PaaS','describe-cloud-service-types/3-describe-platform-service'],['SaaS','describe-cloud-service-types/4-describe-software-service']]},
 {sections:[
 ['Two maps of the same solution','The physical map describes geography, regions, zones, and datacenters. The management map describes management groups, subscriptions, resource groups, and resources. A resource group is an organizational container; it does not by itself create replicas or protect an application against a datacenter outage.'],
 ['Worked example: development and production','A company could separate development and production into subscriptions for distinct access and billing needs. A management group can apply governance across both. Within each subscription, a resource group can hold the related resources for one application. Choose regions and resilience settings separately for those deployed resources.'],
 ['Think in failure boundaries','Distributing supported workloads across zones helps with a zone failure. A regional disaster needs a broader recovery design. Merely knowing that another region exists is not a recovery plan: replication, failover, dependencies, and service support still need consideration. Sovereign regions concern isolated cloud environments and specific requirements, not an extra tier above management groups.']],
 recall:'Will putting two VMs in different resource groups automatically place them in different zones?',answer:'No. Resource groups organize resources. Zone placement is a separate deployment choice.',links:[['Physical infrastructure','describe-core-architectural-components-of-azure/5-describe-azure-physical-infrastructure'],['Management infrastructure','describe-core-architectural-components-of-azure/6-describe-azure-management-infrastructure']]},
 {sections:[
 ['VMs: size versus resilience','Pick VM capacity for workload needs: memory-heavy tasks need sufficient RAM, and CPU-heavy tasks need processing power. A larger VM is still one instance. Scale sets address groups and scaling; availability sets separate maintenance and hardware failure exposure. A fault domain concerns shared hardware risk, while an update domain concerns planned maintenance.'],
 ['Containers: three different levels','For a straightforward container run without maintaining VMs, consider Container Instances. For managed container applications with built-in scaling and load balancing, consider Container Apps. For Kubernetes orchestration of a container fleet, consider AKS. Container packaging helps portability and independent deployment, but does not remove your responsibility for application code and dependencies.'],
 ['Worked example: processing receipts','A shop could host its web API in App Service and use a Function triggered by a receipt upload to process the file. Staff needing a full Windows desktop could use Virtual Desktop. These products solve different needs; “serverless” means the platform handles server operation, not that no servers exist.']],
 recall:'Would an availability set automatically add VMs when traffic increases?',answer:'No. Availability sets separate failure and maintenance domains. Scale sets support managing and scaling a VM group.',links:[['Virtual machines','describe-azure-compute-networking-services/2-virtual-machines'],['Containers','describe-azure-compute-networking-services/5-containers'],['Functions','describe-azure-compute-networking-services/6-functions']]},
 {sections:[
 ['Make three separate choices','First choose the data service: objects, shared files, messages, entities, or VM disks. Next choose an access tier where supported, based on retrieval frequency and delay tolerance. Finally choose redundancy based on the failure boundary you need to survive. Blob tier and storage redundancy answer different questions.'],
 ['Worked example: a media company','New video files accessed daily suit an online, frequently accessed tier. Old footage kept for long-term retention may suit Archive if retrieval delays are acceptable. Editors needing a shared network folder have a file-share requirement instead. Sending a background job to another component is a messaging requirement, which points to Queue Storage.'],
 ['Recovery and movement','ZRS handles zone-level failure within the primary region; geographic options also copy to another region. Cross-region copies can lag, so recent writes may be missing after failover. For moving data, distinguish a command-line copy (AzCopy), graphical browsing (Storage Explorer), ongoing Windows file synchronization (File Sync), and physical bulk transfer (Data Box).']],
 recall:'Can choosing Archive instead of Hot protect against a regional outage?',answer:'No. Access tiers describe access and cost characteristics. Redundancy configuration determines where copies are maintained.',links:[['Storage services and tiers','describe-azure-storage-services/4-describe-azure-storage-services'],['Redundancy','describe-azure-storage-services/3-redundancy'],['File movement','describe-azure-storage-services/7-identify-azure-file-movement-options']]},
 {sections:[
 ['Understand consistency precisely','Strong reads return the latest committed item version. Bounded staleness permits a configured lag. Session provides guarantees within a client session, including reading your own writes. Consistent prefix preserves write order while allowing stale reads. Eventual allows replicas to converge with no new writes. These are trade-offs in freshness, latency, availability, and throughput.'],
 ['Worked example: a changing catalog','A clothing item needs size and fabric properties; a camera needs sensor and lens properties. A flexible document model can accommodate both. A global shop may distribute the data near customers. It still needs a suitable partition key and deliberate consistency choices; global reach alone does not determine whether every reader immediately sees a price change.'],
 ['Capacity is not a user count','A request unit represents the resources an operation consumes, and different operations can have different costs. RU/s expresses a rate of provisioned capacity. A costly query can consume more capacity than a simple item read. Autoscale changes provisioned capacity within limits; serverless is a different billing and capacity approach.']],
 recall:'Does eventual consistency promise that every read immediately sees the newest write?',answer:'No. Replicas converge over time. Strong consistency provides latest-committed-version reads.',links:[['Cosmos DB fundamentals','explore-non-relational-data-stores-azure/2-describe-azure-cosmos-db'],['Consistency levels','https://learn.microsoft.com/en-us/azure/cosmos-db/consistency-levels'],['Request units','https://learn.microsoft.com/en-us/azure/cosmos-db/request-units']]},
 {sections:[
 ['Follow the customer journey','Discovery helps customers find an offer; evaluation lets them assess suitability; purchase establishes commercial terms; deployment makes the solution usable. A listing can support some or all of these steps. A sales-contact listing is not the same experience as an offer transacted through Microsoft commerce.'],
 ['Worked example: choosing a listing','A software vendor that needs to discuss requirements first might use Contact me. A customer who wants hands-on evaluation might choose a trial. A customer with an existing software license might use a BYOL offer. A customer who wants to purchase through the marketplace would look for a transactable offer.'],
 ['Separate business terms from architecture','A private offer describes a customer-specific commercial arrangement. It says nothing by itself about whether the software runs in a public or private cloud. Likewise, a marketplace purchase does not automatically make a solution SaaS. Read the product, licensing, deployment, and infrastructure requirements. Partner Center supports publishers; Marketplace Rewards concerns go-to-market benefits.']],
 recall:'Does “Get it now” always mean the software is free?',answer:'No. The action may involve a paid transaction or an existing license. Check the particular listing.',links:[['Storefronts','intro-commercial-marketplace/3-web-storefronts'],['Listing and engagement options','intro-commercial-marketplace/4-engage-customers'],['Marketplace Rewards','intro-commercial-marketplace/5-go-market-with-microsoft']]}
];
