'use client';
import {useState} from 'react';
import {Button} from '@/components/ui/button';
import {NativeSelect,NativeSelectOption} from '@/components/ui/native-select';
import {Cloud,ArrowRight,BookOpen,Check,RotateCcw,Printer,ExternalLink} from 'lucide-react';
import {topics,questions,matchSets,base} from './content';
import {deeper} from './deeper';
function DeepDive({index}:{index:number}){const note=deeper[index];return <div className="deepdive"><p className="eyebrow">GO A LITTLE DEEPER</p>{note.sections.map(([heading,text])=><section key={heading}><h3>{heading}</h3><p>{text}</p></section>)}<details className="selfcheck"><summary><b>Self-check:</b> {note.recall}<span>Think it through, then reveal the answer</span></summary><p>{note.answer}</p></details><div className="further"><b>Read more on Microsoft Learn</b>{note.links.map(([title,path])=><a key={path} href={path.startsWith('https:')?path:base+path} target="_blank" rel="noreferrer">{title} ↗</a>)}</div></div>}
export default function Home(){
 const [view,setView]=useState('guide');const [topic,setTopic]=useState(0);const [read,setRead]=useState<number[]>([]);
 const [pool,setPool]=useState(questions.map(q=>q.id));const [at,setAt]=useState(0);const [answers,setAnswers]=useState<Record<number,number>>({});const [checked,setChecked]=useState<number[]>([]);const [done,setDone]=useState(false);
 const [round,setRound]=useState(0);const [matches,setMatches]=useState<Record<string,string>>({});const [graded,setGraded]=useState<number[]>([]);
 const q=questions[pool[at]];const t=topics[topic];const m=matchSets[round];const locked=checked.includes(q.id);const missed=pool.filter(id=>answers[id]!==questions[id].answer);const correct=pool.length-missed.length;
 const reset=(ids:number[])=>{setPool(ids);setAt(0);setAnswers({});setChecked([]);setDone(false);setView('quiz')};
 const source=(i:number)=><a href={base+topics[i].source} target="_blank" rel="noreferrer">Microsoft Learn source <ExternalLink size={13}/></a>;
 return <main className="shell"><header><Cloud size={26}/><b>Azure / Study room</b><span>YOUR PERSONAL STUDY COMPANION</span></header><div className="intro"><p className="eyebrow">CLOUD FUNDAMENTALS / FROM YOUR MICROSOFT LEARN READING</p><h1>Understand the cloud.<br/><em>Then put it to the test.</em></h1><p>Nine focused topics. Real-world scenarios. Build your understanding, then see what sticks.</p><div className="actions"><Button onClick={()=>setView('quiz')}>Practice multiple choice <ArrowRight/></Button><Button variant="outline" onClick={()=>reset(questions.filter(x=>x.id>=30).map(x=>x.id))}>Try the 30 new questions</Button><span className="muted">{questions.length} questions + {matchSets.reduce((n,s)=>n+s.pairs.length,0)} matching pairs</span></div></div>
 <nav className="tabs" aria-label="Study modes">{[['guide','Study guide'],['quiz','Multiple choice'],['matching','Matching']].map(([id,label])=><Button key={id} variant="ghost" aria-pressed={view===id} className={view===id?'active':''} onClick={()=>setView(id)}>{label}</Button>)}</nav>
 {view==='guide'&&<div className="workspace"><aside><p className="eyebrow">YOUR STUDY PATH</p>{topics.map((x,i)=><button className={'topic '+(topic===i?'chosen':'')} key={x.title} onClick={()=>setTopic(i)} aria-current={topic===i?'true':undefined}><span>{String(i+1).padStart(2,'0')}</span>{x.short}{read.includes(i)&&<Check size={15}/>}</button>)}<p className="muted small">{read.length} of 9 marked reviewed<br/>Progress lasts for this visit.</p><Button variant="outline" onClick={()=>window.print()}><Printer/> Print full guide</Button></aside><div><article className="panel"><div className="sectionhead"><p className="eyebrow">STUDY NOTE {String(topic+1).padStart(2,'0')}</p><span className="pill">ESSENTIALS</span></div><h2>{t.title}</h2><p className="lead">{t.lead}</p><dl>{t.rows.map(([label,text])=><div className="entry" key={label}><dt>{label}</dt><dd>{text}</dd></div>)}</dl><DeepDive index={topic}/><div className="callout"><b>Keep this in mind</b><br/>{t.tip}</div><div className="source">{source(topic)}</div><div className="actions"><Button variant="outline" onClick={()=>reset(questions.filter(x=>x.topic===topic).map(x=>x.id))}>Practice this topic</Button><Button variant="outline" onClick={()=>setRead(read.includes(topic)?read.filter(i=>i!==topic):[...read,topic])}><Check/>{read.includes(topic)?'Reviewed':'Mark reviewed'}</Button><Button onClick={()=>topic<8?setTopic(topic+1):setView('quiz')}>{topic<8?'Next topic':'Try the quiz'}<ArrowRight/></Button></div></article><div className="small muted">Study approach: read a topic, explain it in your own words, then practice. Questions are original study exercises, not official exam questions.</div></div></div>}
 {view==='quiz'&&<section className="quizarea"><div className="quizmeta"><span className="eyebrow">MULTIPLE CHOICE</span><span>{done?'Review your results':`${at+1} / ${pool.length}`}</span></div><progress aria-label="Questions checked" value={checked.length} max={pool.length}/>{done?<article className="panel"><p className="eyebrow">PRACTICE COMPLETE</p><h2 className="score">{Math.round(correct/pool.length*100)}% <small>{correct} / {pool.length} correct</small></h2><p>{missed.length?'Use the explanations below to revisit the ideas that need another pass.':'Excellent work. Try matching next to strengthen your recall.'}</p><div className="actions">{missed.length>0&&<Button onClick={()=>reset(missed)}>Retry {missed.length} missed questions</Button>}<Button variant="outline" onClick={()=>reset(questions.map(x=>x.id))}><RotateCcw/> Restart all {questions.length}</Button><Button variant="outline" onClick={()=>setView('matching')}>Try matching</Button></div><div className="results">{pool.map(id=>{const item=questions[id];const ok=answers[id]===item.answer;return <details key={id}><summary><span className={ok?'goodtext':'badtext'}>{ok?'Correct':'Review'}</span> {item.q}</summary><p>Your answer: {item.options[answers[id]]??'Not answered'}</p><p><b>Correct answer: {item.options[item.answer]}</b><br/>{item.why}</p>{source(item.topic)}</details>})}</div></article>:<article className="panel"><p className="eyebrow">{topics[q.topic].short}</p><h2>{q.q}</h2><p className="small muted">Choose one answer, then check it. Your checked answer is final for this attempt.</p><fieldset className="options"><legend className="sr-only">Choose your answer</legend>{q.options.map((option,i)=><label key={option} className={'option '+(answers[q.id]===i?'selected ':'')+(locked&&i===q.answer?'right ':'')+(locked&&answers[q.id]===i&&i!==q.answer?'wrong':'')}><input type="radio" name={'question'+q.id} value={i} checked={answers[q.id]===i} disabled={locked} onChange={()=>setAnswers({...answers,[q.id]:i})}/><span className="letter">{'ABCD'[i]}</span><span>{option}</span>{locked&&i===q.answer&&<Check size={18}/>}</label>)}</fieldset>{locked&&<div className={'feedback '+(answers[q.id]===q.answer?'good':'bad')} role="status"><b>{answers[q.id]===q.answer?'Correct.':'Not quite.'}</b> {q.why}<div className="source">{source(q.topic)}</div></div>}<div className="actions spread"><Button variant="outline" disabled={at===0} onClick={()=>setAt(at-1)}>Previous</Button>{!locked?<Button disabled={answers[q.id]===undefined} onClick={()=>setChecked([...checked,q.id])}>Check answer</Button>:<Button onClick={()=>at===pool.length-1?setDone(true):setAt(at+1)}>{at===pool.length-1?'See results':'Next question'}<ArrowRight/></Button>}</div></article>}</section>}
 {view==='matching'&&<section className="quizarea"><div className="quizmeta"><p className="eyebrow">MATCHING LAB</p><span>Round {round+1} of {matchSets.length}</span></div><article className="panel"><h2>{m.title}</h2><p className="muted">Match each term to its definition. Each definition is used once. One point per correct pair.</p><div className="roundnav">{matchSets.map((s,i)=><Button key={s.title} variant={round===i?'default':'outline'} onClick={()=>setRound(i)} aria-label={'Round '+(i+1)+': '+s.title}>{i+1}{graded.includes(i)&&<Check size={13}/>}</Button>)}</div>{m.pairs.map(([term,definition],i)=>{const key=round+'-'+i;const isChecked=graded.includes(round);return <div className="matchrow" key={key}><label htmlFor={'match-'+key}>{term}</label><div><NativeSelect id={'match-'+key} value={matches[key]??''} disabled={isChecked} onChange={e=>setMatches({...matches,[key]:e.target.value})}><NativeSelectOption value="">Select a definition…</NativeSelectOption>{[...m.pairs].sort((a,b)=>a[1].localeCompare(b[1])).map(([,d])=><NativeSelectOption key={d} value={d}>{d}</NativeSelectOption>)}</NativeSelect>{isChecked&&<p className={'small '+(matches[key]===definition?'goodtext':'badtext')}>{matches[key]===definition?'Correct':'Correct match: '+definition}</p>}</div></div>})}<div aria-live="polite">{graded.includes(round)&&<div className="feedback good"><b>{m.pairs.filter(([,d],i)=>matches[round+'-'+i]===d).length} / {m.pairs.length} pairs correct.</b> Review the definitions above, then try again.</div>}</div><div className="actions">{!graded.includes(round)?<Button disabled={!m.pairs.every((_,i)=>matches[round+'-'+i])} onClick={()=>setGraded([...graded,round])}>Check matches</Button>:<><Button variant="outline" onClick={()=>{setGraded(graded.filter(x=>x!==round));setMatches(Object.fromEntries(Object.entries(matches).filter(([k])=>!k.startsWith(round+'-'))))}}><RotateCcw/> Retry round</Button>{round<matchSets.length-1&&<Button onClick={()=>setRound(round+1)}>Next round<ArrowRight/></Button>}</>}</div><p className="small muted">Total checked score: {matchSets.reduce((n,s,r)=>n+(graded.includes(r)?s.pairs.filter(([,d],i)=>matches[r+'-'+i]===d).length:0),0)} / {graded.length*5} pairs across {graded.length} checked rounds.</p><div className="source">{source(m.topic)}</div></article></section>}
 <section className="printguide"><h1>Azure Study Room — Study guide</h1>{topics.map((s,i)=><article key={s.title}><h2>{i+1}. {s.title}</h2><p>{s.lead}</p>{s.rows.map(([a,b])=><p key={a}><b>{a}: </b>{b}</p>)}<DeepDive index={i}/><p><b>Remember: </b>{s.tip}</p><a href={base+s.source}>{base+s.source}</a></article>)}</section><footer><BookOpen size={18}/><p>Based on your Microsoft Learn reading · Reviewed September 18, 2026<br/><span className="small">Independent study aid. Source links in each topic open the assigned reading. Quiz answers and progress stay in this visit and reset on refresh.</span></p></footer></main>
}
