import {useState} from 'react';
import {Button} from '@/components/ui/button';
import {Textarea} from '@/components/ui/textarea';
import type {Pack} from './schema';

export function ShortAnswers({pack}:{pack:Pack}){
 const questions=pack.shortAnswers??[];
 const [index,setIndex]=useState(0);
 const [answers,setAnswers]=useState<Record<number,string>>({});
 const [revealed,setRevealed]=useState<Record<number,boolean>>({});
 const [ratings,setRatings]=useState<Record<number,number>>({});
 if(!questions.length)return <article className="panel quizarea"><h2>No short-answer questions in this pack</h2><p>Create a new pack with short-answer questions enabled to practice explaining ideas in your own words.</p></article>;
 const q=questions[index];const reviewed=Object.keys(ratings).length;
 return <section className="quizarea"><div className="quizmeta"><span className="eyebrow">SHORT ANSWER</span><span>{index+1} / {questions.length}</span></div><progress value={reviewed} max={questions.length} aria-label="Short answers self-assessed"/><article className="panel"><p className="eyebrow">{pack.lessons[q.lesson]?.title}</p><h2>{q.q}</h2><p className="muted">Explain in your own words, then compare with the model answer. This practice is self-assessed.</p><label htmlFor="short-response">Your response</label><Textarea id="short-response" rows={6} maxLength={8000} value={answers[index]??''} disabled={revealed[index]} onChange={e=>setAnswers({...answers,[index]:e.target.value})}/>{!revealed[index]?<Button disabled={!answers[index]?.trim()} onClick={()=>setRevealed({...revealed,[index]:true})}>Reveal model answer</Button>:<div className="callout"><h3>Model answer</h3><p>{q.answer}</p><h3>Key points to include</h3><ul>{q.keyPoints.map((point,i)=><li key={i}>{point}</li>)}</ul><p className="small muted">Equivalent wording is fine. Check the ideas and reasoning, not an exact text match.</p><div className="source references">{q.sourceIds.map(id=><span key={id}>{pack.sources[id]?.url?<a href={pack.sources[id].url} target="_blank" rel="noreferrer">{pack.sources[id].title}</a>:pack.sources[id]?.title}</span>)}</div><p><b>How well did your answer cover the key points?</b></p><div className="actions">{['Needs practice','Partly covered','Covered well'].map((label,value)=><Button key={label} variant={ratings[index]===value?'default':'outline'} aria-pressed={ratings[index]===value} onClick={()=>setRatings({...ratings,[index]:value})}>{label}</Button>)}</div></div>}<div className="actions spread"><Button variant="outline" disabled={index===0} onClick={()=>setIndex(index-1)}>Previous question</Button><Button variant="outline" disabled={index===questions.length-1} onClick={()=>setIndex(index+1)}>Next question</Button></div><p aria-live="polite">{reviewed} / {questions.length} self-assessed{reviewed===questions.length?` - ${Object.values(ratings).filter(v=>v===2).length} covered well, ${Object.values(ratings).filter(v=>v===1).length} partly covered, ${Object.values(ratings).filter(v=>v===0).length} need practice.`:'.'}</p><Button variant="outline" onClick={()=>{setAnswers({});setRevealed({});setRatings({});setIndex(0);}}>Start a new short-answer attempt</Button></article></section>;
}
