import {useEffect,useRef,useState} from 'react';
import {BookOpen,Plus,Settings,ArrowRight,Download,Upload,Check,RotateCcw,Printer,ExternalLink,Library,Power,X} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {NativeSelect,NativeSelectOption} from '@/components/ui/native-select';
import type {Pack,Source} from './schema';
type Card={id:string;title:string;description:string;createdAt:string;questions:number;matches:number};
async function api<T>(url:string,body?:unknown,signal?:AbortSignal):Promise<T>{const r=await fetch(url,{method:body===undefined?'GET':'POST',headers:body===undefined?{}:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body),signal});const data=await r.json() as T & {error?:string};if(!r.ok)throw new Error(data.error||'The app could not complete that request.');return data;}
function download(pack:Pack){const blob=new Blob([JSON.stringify(pack,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=(pack.title.replace(/[^a-z0-9 -]/gi,'').slice(0,60)||'Study pack')+'.study.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
function Refs({pack,ids}:{pack:Pack;ids:number[]}){return <div className="source references">{ids.map(id=>{const s=pack.sources[id];return s&&<span key={id}>{s.url?<a href={s.url} target="_blank" rel="noreferrer">{s.title}<ExternalLink size={12}/></a>:<span>{s.title} · pasted text</span>}</span>})}</div>}
function Lesson({pack,index}:{pack:Pack;index:number}){const l=pack.lessons[index];return <article className="panel lesson"><p className="eyebrow">LESSON {index+1}</p><h2>{l.title}</h2><p className="lead">{l.summary}</p><dl>{l.concepts.map((c,i)=><div className="entry" key={i}><dt>{c.term}</dt><dd>{c.explanation}</dd></div>)}</dl><div className="deepdive">{l.sections.map((s,i)=><section key={i}><h3>{s.heading}</h3><p>{s.text}</p></section>)}</div><div className="callout"><b>Remember</b><p>{l.takeaway}</p></div><details className="selfcheck"><summary><b>Self-check:</b> {l.selfCheck}<span>Reveal the answer</span></summary><p>{l.selfAnswer}</p></details><Refs pack={pack} ids={l.sourceIds}/></article>}
export function StudyView({pack,onBack}:{pack:Pack;onBack:()=>void}){
 const [mode,setMode]=useState('guide');const [lesson,setLesson]=useState(0);const [pool,setPool]=useState(pack.questions.map((_,i)=>i));const [index,setIndex]=useState(0);const [answers,setAnswers]=useState<Record<number,number>>({});const [checked,setChecked]=useState<number[]>([]);const [done,setDone]=useState(false);
 const [round,setRound]=useState(0);const [selections,setSelections]=useState<Record<number,string>>({});const [graded,setGraded]=useState<number[]>([]);
 const id=pool[index],q=pack.questions[id],locked=checked.includes(id);const missed=pool.filter(i=>answers[i]!==pack.questions[i].answer);
 const rounds=Array.from({length:Math.ceil(pack.matches.length/5)},(_,r)=>pack.matches.slice(r*5,r*5+5));const current=rounds[round];
 const start=(ids:number[])=>{if(!ids.length)return;setPool(ids);setIndex(0);setAnswers({});setChecked([]);setDone(false);setMode('quiz')};
 return <div><div className="packtoolbar"><Button variant="ghost" onClick={onBack}>← Library</Button><div className="actions"><Button variant="outline" onClick={()=>download(pack)}><Download/>Export pack</Button><Button variant="outline" onClick={()=>window.print()}><Printer/>Print guide</Button></div></div><div className="packheading"><p className="eyebrow">YOUR STUDY PACK</p><h1>{pack.title}</h1><p>{pack.description}</p><span className="muted small">{pack.lessons.length} lessons · {pack.questions.length} questions · {pack.matches.length} matching pairs · {pack.sources.length} sources</span></div><nav className="tabs" aria-label="Study activity">{[['guide','Study guide'],['quiz','Multiple choice'],['matching','Matching']].map(([v,label])=><Button key={v} variant="ghost" className={mode===v?'active':''} aria-pressed={mode===v} onClick={()=>setMode(v)}>{label}</Button>)}</nav>
 {mode==='guide'&&<div className="workspace"><aside><p className="eyebrow">LESSONS</p>{pack.lessons.map((l,i)=><button key={i} className={'topic '+(lesson===i?'chosen':'')} onClick={()=>setLesson(i)} aria-current={lesson===i?'true':undefined}><span>{i+1}</span>{l.title}</button>)}</aside><div><Lesson pack={pack} index={lesson}/><div className="actions"><Button variant="outline" disabled={lesson===0} onClick={()=>setLesson(lesson-1)}>Previous lesson</Button><Button onClick={()=>lesson<pack.lessons.length-1?setLesson(lesson+1):setMode('quiz')}>{lesson<pack.lessons.length-1?'Next lesson':'Start quiz'}<ArrowRight/></Button>{pack.questions.some(q=>q.lesson===lesson)&&<Button variant="outline" onClick={()=>start(pack.questions.map((q,i)=>q.lesson===lesson?i:-1).filter(i=>i>=0))}>Practice this lesson</Button>}</div></div></div>}
 {mode==='quiz'&&<div className="quizarea"><div className="quizmeta"><span className="eyebrow">MULTIPLE CHOICE</span><span>{done?'Results':`${index+1} / ${pool.length}`}</span></div><progress value={checked.length} max={pool.length} aria-label="Questions answered"/>{done?<article className="panel"><h2 className="score">{Math.round((pool.length-missed.length)/pool.length*100)}%<small>{pool.length-missed.length} / {pool.length} correct</small></h2><div className="actions">{missed.length>0&&<Button onClick={()=>start(missed)}>Retry {missed.length} missed</Button>}<Button variant="outline" onClick={()=>start(pack.questions.map((_,i)=>i))}><RotateCcw/>All questions</Button><Button variant="outline" onClick={()=>setMode('matching')}>Try matching</Button></div><div className="results">{pool.map(i=><details key={i}><summary><b className={answers[i]===pack.questions[i].answer?'goodtext':'badtext'}>{answers[i]===pack.questions[i].answer?'Correct':'Review'}</b> {pack.questions[i].q}</summary><p>Your answer: {pack.questions[i].options[answers[i]]}</p><p><b>Correct: {pack.questions[i].options[pack.questions[i].answer]}</b></p><p>{pack.questions[i].why}</p><Refs pack={pack} ids={pack.questions[i].sourceIds}/></details>)}</div></article>:<article className="panel"><p className="eyebrow">{pack.lessons[q.lesson]?.title}</p><h2>{q.q}</h2><p className="muted small">Choose one answer. Check it to see the explanation.</p><fieldset className="options"><legend className="sr-only">Your answer</legend>{q.options.map((option,i)=><label key={i} className={'option '+(answers[id]===i?'selected ':'')+(locked&&q.answer===i?'right ':'')+(locked&&answers[id]===i&&q.answer!==i?'wrong':'')}><input type="radio" name="answer" checked={answers[id]===i} disabled={locked} onChange={()=>setAnswers({...answers,[id]:i})}/><span className="letter">{'ABCD'[i]}</span><span>{option}</span>{locked&&q.answer===i&&<Check size={18}/>}</label>)}</fieldset>{locked&&<div role="status" className={'feedback '+(answers[id]===q.answer?'good':'bad')}><b>{answers[id]===q.answer?'Correct.':'Not quite.'}</b> {q.why}<Refs pack={pack} ids={q.sourceIds}/></div>}<div className="actions spread"><Button variant="outline" disabled={index===0} onClick={()=>setIndex(index-1)}>Previous</Button>{locked?<Button onClick={()=>index===pool.length-1?setDone(true):setIndex(index+1)}>{index===pool.length-1?'See results':'Next'}<ArrowRight/></Button>:<Button disabled={answers[id]===undefined} onClick={()=>setChecked([...checked,id])}>Check answer</Button>}</div></article>}</div>}
 {mode==='matching'&&<div className="quizarea"><article className="panel"><p className="eyebrow">MATCHING · ROUND {round+1} OF {rounds.length}</p><h2>Connect each term to its meaning.</h2><p className="muted">Use each definition once. One point per correct pair.</p><div className="roundnav">{rounds.map((_,i)=><Button key={i} variant={round===i?'default':'outline'} onClick={()=>setRound(i)} aria-label={'Round '+(i+1)}>{i+1}{graded.includes(i)&&<Check size={12}/>}</Button>)}</div>{current.map((m,i)=>{const key=round*5+i;return <div className="matchrow" key={key}><label htmlFor={'match'+key}>{m.term}</label><div><NativeSelect id={'match'+key} value={selections[key]??''} disabled={graded.includes(round)} onChange={e=>setSelections({...selections,[key]:e.target.value})}><NativeSelectOption value="">Choose a definition…</NativeSelectOption>{[...current].sort((a,b)=>a.definition.localeCompare(b.definition)).map((opt,k)=><NativeSelectOption key={k} value={opt.definition}>{opt.definition}</NativeSelectOption>)}</NativeSelect>{graded.includes(round)&&<div className="small"><p className={selections[key]===m.definition?'goodtext':'badtext'}>{selections[key]===m.definition?'Correct':'Correct match: '+m.definition}</p><p>{m.why}</p><Refs pack={pack} ids={m.sourceIds}/></div>}</div></div>})}<div aria-live="polite">{graded.includes(round)&&<p className="feedback good">{current.filter((m,i)=>selections[round*5+i]===m.definition).length} / {current.length} correct in this round.</p>}</div><div className="actions">{!graded.includes(round)?<Button disabled={!current.every((_,i)=>selections[round*5+i])} onClick={()=>setGraded([...graded,round])}>Check matches</Button>:<><Button variant="outline" onClick={()=>{setGraded(graded.filter(r=>r!==round));setSelections(Object.fromEntries(Object.entries(selections).filter(([k])=>Math.floor(Number(k)/5)!==round)))}}>Retry round</Button>{round<rounds.length-1&&<Button onClick={()=>setRound(round+1)}>Next round<ArrowRight/></Button>}</>}</div></article></div>}
 <div className="printguide"><h1>{pack.title}</h1>{pack.lessons.map((_,i)=><Lesson pack={pack} index={i} key={i}/>)}</div></div>
}
export default function App(){
 const [page,setPage]=useState('library');const [cards,setCards]=useState<Card[]>([]);const [pack,setPack]=useState<Pack|null>(null);const [error,setError]=useState('');const [ready,setReady]=useState(false);const [quit,setQuit]=useState(false);
 const [key,setKey]=useState('');const [model,setModel]=useState('gpt-5-mini');const [urls,setUrls]=useState('');const [sources,setSources]=useState<Source[]>([]);const [failures,setFailures]=useState<{url:string;error:string}[]>([]);
 const [questionCount,setQuestionCount]=useState(20);const [matchCount,setMatchCount]=useState(10);const [depth,setDepth]=useState('detailed');const [stage,setStage]=useState('');const [elapsed,setElapsed]=useState(0);const [manualTitle,setManualTitle]=useState('');const [manualText,setManualText]=useState('');
 const controller=useRef<AbortController|null>(null);const importRef=useRef<HTMLInputElement>(null);
 async function library(){setCards(await api<Card[]>('/api/packs'));}
 useEffect(()=>{let active=true;(async()=>{try{const token=location.hash.slice(1);if(token){const r=await fetch('/api/session',{method:'POST',headers:{'X-Study-Token':token}});if(!r.ok)throw new Error('Reopen Study Room.exe to start a session.');history.replaceState(null,'',location.pathname);}const list=await api<Card[]>('/api/packs');if(active){setCards(list);setReady(true);}}catch(e){if(active)setError((e as Error).message);}})();const heart=setInterval(()=>{api('/api/heartbeat').catch(()=>{});},60000);return()=>{active=false;clearInterval(heart);};},[]);
 useEffect(()=>{if(!stage)return;setElapsed(0);const timer=setInterval(()=>setElapsed(n=>n+1),1000);return()=>clearInterval(timer);},[stage]);
 const capture=(e:unknown)=>setError(e instanceof Error?(e.name==='AbortError'?'Cancelled. No new pack was saved.':e.message):'Something went wrong.');
 async function generate(selected:Source[],signal:AbortSignal){if(!key.trim())throw new Error('Add your OpenAI API key in Settings first.');if(!selected.length)throw new Error('Add at least one readable article or paste article text.');setStage('Generating your guide, quiz, and matching exercises');const p=await api<Pack>('/api/generate',{apiKey:key.trim(),model:model.trim(),sources:selected,questionCount,matchCount,depth},signal);setPack(p);setPage('study');await library();}
 async function begin(readFirst:boolean){setError('');const c=new AbortController();controller.current=c;try{if(!Number.isInteger(questionCount)||questionCount<1||questionCount>120)throw new Error('Choose a whole number of questions from 1 to 120.');let chosen=sources;if(readFirst&&urls.trim()){const list=[...new Set((urls.match(/https?:\/\/[^\s<>\[\]()]+/gi)||[]))];if(!list.length)throw new Error('Paste at least one complete http or https URL.');if(list.length>10)throw new Error('Use up to 10 article URLs at a time.');if(list.some(s=>!/^https?:\/\//i.test(s)))throw new Error('Enter complete http or https URLs, one per line.');setStage('Reading your articles');const result=await api<{results:({ok:true;source:Source}|{ok:false;url:string;error:string})[]}>('/api/read',{urls:list},c.signal);chosen=[...sources.filter(s=>!s.url),...result.results.flatMap(r=>r.ok?[r.source]:[])];setSources(chosen);const failed=result.results.flatMap(r=>r.ok?[]:[{url:r.url,error:r.error}]);setFailures(failed);if(failed.length){setError('Some articles could not be read. Review the sources below, paste missing text, or generate from the readable sources.');return;}}await generate(chosen,c.signal);}catch(e){capture(e);}finally{setStage('');controller.current=null;}}
 async function open(id:string){setError('');try{setPack(await api<Pack>('/api/packs/'+id));setPage('study');}catch(e){capture(e);}}
 async function importPack(file:File){setError('');try{if(file.size>2_000_000)throw new Error('Study pack is too large (maximum 2 MB).');const saved=await api<Pack>('/api/import',JSON.parse(await file.text()));setPack(saved);setPage('study');await library();}catch(e){capture(e);}}
 function addManual(){if(manualText.trim().length<100){setError('Paste at least 100 characters of article text.');return;}if(sources.length>=10){setError('Use up to 10 sources per pack.');return;}setSources([...sources,{title:manualTitle.trim()||'Pasted article',url:'',text:manualText.slice(0,30000),truncated:manualText.length>30000}]);setManualTitle('');setManualText('');setError('');}
 if(quit)return <main className="shell"><article className="panel"><h1>Study Room is closed.</h1><p>Your saved packs are in the portable folder. Reopen Study Room.exe whenever you want to continue.</p></article></main>;
 return <main className="shell portable"><header><BookOpen size={26}/><b>Study Room</b><span className="localbadge">PORTABLE · WINDOWS</span><nav aria-label="Main navigation"><Button variant={page==='library'?'secondary':'ghost'} disabled={!!stage} onClick={()=>{setPage('library');setError('');}}><Library/>Library</Button><Button variant={page==='new'?'secondary':'ghost'} disabled={!!stage} onClick={()=>{setPage('new');setError('');}}><Plus/>New pack</Button><Button variant={page==='settings'?'secondary':'ghost'} disabled={!!stage} onClick={()=>{setPage('settings');setError('');}}><Settings/>Settings</Button></nav></header>
 {error&&<div className="feedback bad errorbanner" role="alert"><span>{error}</span><Button variant="ghost" aria-label="Dismiss error" onClick={()=>setError('')}><X/></Button></div>}
 {!ready?<div className="panel"><h2>Opening your study library…</h2><p>If this does not load, close this tab and reopen Study Room.exe.</p></div>:<>
 {page==='library'&&<><div className="intro"><p className="eyebrow">YOUR ARTICLES. YOUR STUDY ROOM.</p><h1>Turn what you read<br/><em>into what you remember.</em></h1><p>Paste article links to create a clear study guide, a multiple-choice quiz, and matching practice. Keep every pack in your portable library.</p><div className="actions"><Button onClick={()=>setPage('new')}><Plus/>Create a study pack</Button><Button variant="outline" onClick={()=>importRef.current?.click()}><Upload/>Import pack</Button></div></div><div className="libraryheading"><h2>Your library</h2><span className="muted small">{cards.length} saved {cards.length===1?'pack':'packs'}</span></div><div className="librarygrid">{cards.map(c=><article className="panel librarycard" key={c.id}><p className="eyebrow">{c.id==='azure-starter'?'INCLUDED STUDY PACK':'SAVED STUDY PACK'}</p><h3>{c.title}</h3><p>{c.description}</p><div className="small muted">{c.questions} questions · {c.matches} matching pairs</div><Button onClick={()=>open(c.id)}>Open study pack<ArrowRight/></Button></article>)}{!cards.length&&<article className="panel"><h3>Your first pack starts with a link.</h3><p>Create a new pack or import one you exported earlier.</p></article>}</div></>}
 {page==='settings'&&<section className="formarea"><div className="intro"><p className="eyebrow">GENERATION SETTINGS</p><h1>Bring your API key.</h1><p>The key is kept only in this tab’s memory. It is sent to your local app and then directly to OpenAI when you generate a pack. It is never included in saved packs.</p></div><article className="panel"><label htmlFor="apikey">OpenAI API key</label><Input id="apikey" type="password" autoComplete="off" spellCheck={false} value={key} onChange={e=>setKey(e.target.value)} placeholder="sk-…"/><p className="small muted">API usage is billed to your OpenAI API account. A ChatGPT subscription does not supply an API key. <a href="https://platform.openai.com/api-keys" target="_blank" rel="noreferrer">Create or manage keys ↗</a></p><label htmlFor="model">Model</label><Input id="model" value={model} onChange={e=>setModel(e.target.value)} spellCheck={false}/><p className="small muted">Default: gpt-5-mini. Use a model available to your API project that supports the Responses API and structured output.</p><div className="actions"><Button onClick={()=>setPage('new')}>Continue to new pack<ArrowRight/></Button><Button variant="outline" onClick={()=>setKey('')}>Forget key</Button></div></article><div className="callout"><b>What is sent?</b><p>Only the sources selected for the current pack, your generation settings, and your API key for authentication. Generation uses store: false. Reading an article does not send your API key to that article’s website.</p></div></section>}
 {page==='new'&&<section className="formarea"><div className="intro"><p className="eyebrow">CREATE SOMETHING YOU CAN LEARN FROM</p><h1>Paste links. Start learning.</h1><p>Up to 10 public HTML articles, one URL per line. For blocked pages, PDFs, or pages requiring sign-in, paste the article text below.</p></div><article className="panel"><label htmlFor="urls">Article URLs</label><Textarea id="urls" rows={5} value={urls} disabled={!!stage} onChange={e=>setUrls(e.target.value)} placeholder={'https://example.com/article-one\nhttps://example.com/article-two'}/><p className="small muted">Microsoft Learn module links automatically include their lessons. Plain URLs and pasted Markdown links are supported.</p><div className="settingsgrid"><div><label htmlFor="count">Multiple-choice questions</label><Input id="count" type="number" min={1} max={120} step={1} value={questionCount||''} disabled={!!stage} onChange={e=>setQuestionCount(Number(e.target.value))} aria-describedby="count-help"/><p id="count-help" className="small muted">Choose any whole number from 1 to 120. Larger quizzes take longer and use more API credits.</p></div><div><label htmlFor="pairs">Matching pairs</label><NativeSelect id="pairs" value={matchCount} disabled={!!stage} onChange={e=>setMatchCount(Number(e.target.value))}>{[5,10,15,20].map(n=><NativeSelectOption key={n} value={n}>{n} pairs</NativeSelectOption>)}</NativeSelect></div><div><label htmlFor="depth">Guide depth</label><NativeSelect id="depth" value={depth} disabled={!!stage} onChange={e=>setDepth(e.target.value)}><NativeSelectOption value="detailed">Detailed, with examples</NativeSelectOption><NativeSelectOption value="concise">Concise review</NativeSelectOption></NativeSelect></div></div>{!key&&<p className="keyhint">Add an API key in <button onClick={()=>setPage('settings')}>Settings</button> before generating.</p>}<div className="actions"><Button disabled={!!stage||!key||(!urls.trim()&&!sources.length)} onClick={()=>begin(true)}>Generate study pack<ArrowRight/></Button>{sources.length>0&&<Button variant="outline" disabled={!!stage||!key} onClick={()=>begin(false)}>Generate from {sources.length} loaded sources</Button>}</div><p className="small muted">Generation sends the selected article text to OpenAI and uses your API balance. Text is limited to 30,000 characters per source and 160,000 per pack.</p></article>
 {stage&&<div className="panel progresspanel" role="status" aria-live="polite"><span className="spinner"/><div><b>{stage}…</b><p>{elapsed}s elapsed · Larger packs can take several minutes.</p></div><Button variant="outline" onClick={()=>controller.current?.abort()}>Cancel</Button></div>}
 {failures.length>0&&<article className="panel"><h3>Articles needing attention</h3>{failures.map((f,i)=><div className="failedsource" key={i}><b>{f.url}</b><p>{f.error}</p></div>)}</article>}
 {sources.length>0&&<article className="panel"><h2>Loaded sources</h2><p className="muted small">Review or edit the text the generator will use. Removing a loaded source affects “Generate from loaded sources”; reading URLs again reloads those pages.</p>{sources.map((s,i)=><details className="sourcepreview" key={i}><summary>{s.title} <span className="muted small">{s.unitUrls?.length?`${s.unitUrls.length} lessons ? `:''}{s.text.length.toLocaleString()} characters{s.truncated?' · trimmed to limit':''}</span></summary><p className="small">{s.url||'Manually pasted text'}</p><Textarea aria-label={'Source text for '+s.title} rows={8} value={s.text} disabled={!!stage} onChange={e=>setSources(sources.map((x,j)=>i===j?{...x,text:e.target.value.slice(0,30000)}:x))}/><Button variant="ghost" disabled={!!stage} onClick={()=>setSources(sources.filter((_,j)=>j!==i))}>Remove source</Button></details>)}</article>}
 <details className="panel manual"><summary>Paste article text instead</summary><label htmlFor="manualTitle">Article title</label><Input id="manualTitle" value={manualTitle} disabled={!!stage} onChange={e=>setManualTitle(e.target.value)}/><label htmlFor="manualText">Article text</label><Textarea id="manualText" rows={8} value={manualText} disabled={!!stage} onChange={e=>setManualText(e.target.value)}/><div className="actions"><Button variant="outline" disabled={!!stage} onClick={addManual}>Add text as a source</Button></div></details></section>}
 {page==='study'&&pack&&<StudyView key={pack.id} pack={pack} onBack={()=>setPage('library')}/>}</>}
 <input ref={importRef} hidden type="file" accept=".json,.study.json" onChange={e=>{const f=e.target.files?.[0];if(f)void importPack(f);e.target.value='';}}/>
 <footer><BookOpen size={18}/><p>Saved packs live in this app’s data folder. Copy the whole folder to take your library with you.<br/><span className="small">Generated content can contain mistakes. Use the source links to check important details. Quiz progress resets when you leave a pack.</span></p><Button variant="ghost" disabled={!!stage} onClick={async()=>{try{await api('/api/quit',{});setKey('');setQuit(true);}catch(e){capture(e);}}}><Power/>Quit app</Button></footer></main>;
}
